name: desafio_flutter_urbetrack
description: A new Flutter project made for Urbetrack.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  dio: 5.3.3
  get_it: 7.6.4
  flutter_dotenv: 5.1.0
  flutter_bloc: 8.1.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  mockito: 5.4.2
  bloc_test: 9.1.4
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.6

  flutter_lints: 2.0.0
  freezed: 2.4.5
  json_serializable: 6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/i18n/
    - assets/icons/
